import { Metadata } from "next";
import React from "react";
import { navItems } from "../../lib/categories"

type MetadataProps = {
  params: { categoryId: string }
}

export async function generateMetadata({ params }: MetadataProps): Promise<Metadata> {

  const title = navItems.filter(nav => nav.path === params.categoryId)  

  return {
      title: title[0].label,
      description: "Generated by create next app",
    };
}


const CategoryLayout = ({ children }: { children: React.ReactNode }) => {
  return <div>{children}</div>;
};

export default CategoryLayout;
