import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Kategorija",

  description: "Generated by create next app",
};

const CategoryLayout = ({ children }: { children: React.ReactNode }) => {
  return <div>{children}</div>;
};

export default CategoryLayout;
