import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Tag",
  description: "Generated by create next app",
};

const CategoryLayout = ({ children }: { children: React.ReactNode }) => {
  return <main className="w-full md:w-[80%] lg:w-[800px] mt-4 mx-auto min-h-svh overflow-hidden">{children}</main>;
};

export default CategoryLayout;
