import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import NavBar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import CategoryMenu from "@/components/navbar/category-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: process.env.title as string,
    template: `%s | ${process.env.title as string}`,
  },

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <NavBar />
        <CategoryMenu />
        <main className="w-full md:w-[80%] lg:w-[900px]  mx-auto min-h-svh overflow-hidden">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
