import { SinglePostAPI } from "@/lib/api-types";
import { Metadata } from "next";
import React from "react";

type MetadataProps = {
    params: { slug: string }
    searchParams: { [key: string]: string | string[] | undefined }
  }

export async function generateMetadata({params, searchParams}: MetadataProps): Promise<Metadata> {

    const postListRes = await fetch(`http://localhost:3000/api/posts/${params.slug}/`, { cache: "no-store" });
    const postListData: SinglePostAPI = await postListRes.json();
  

    return {
        title: `${postListData.data.post.title} | ${process.env.title as string}`,
        description: "Generated by create next app",
      };
}


const SinglePostLayout = ({ children }: { children: React.ReactNode }) => {
  return <div>{children}</div>;
};

export default SinglePostLayout;
