import { SinglePostAPI } from "@/lib/api-types";
import { Metadata } from "next";
import React from "react";

type MetadataProps = {
    params: { slug: string }
    searchParams: { [key: string]: string | string[] | undefined }
  }

export async function generateMetadata({params, searchParams}: MetadataProps): Promise<Metadata> {

    const postListRes = await fetch(`http://localhost:3000/api/posts/${params.slug}/`, { cache: "no-store" });
    const postListData: SinglePostAPI = await postListRes.json();

    const keywordArr = postListData.data.post.seo.focuskw.split(" ")
    console.log(keywordArr);
    

    return {
        title: `${postListData.data.post.title} | ${process.env.title as string}`,
        description: "Generated by create next app",
        authors: [{name: postListData.data.post.author.node.name}],
        keywords: keywordArr
      };
}


const SinglePostLayout = ({ children }: { children: React.ReactNode }) => {
  return <main className="mx-auto mb-6">{children}</main>;
};

export default SinglePostLayout;
